import cookie from 'js-cookie'
var all = {
  cn: {
    'operateSuccess': '操作成功！',
    'showAuth': '显示控制',
    'list': '列表',
    'inputField': '请输入字段名',
    'fieldName': '字段名',
    'pageId': '页面ID',
    'detail': '详情',
    'edit': '编辑',
    'search': '搜索',
    'numberMessage': '请输入数字',
    'longTextMessage': '请输入小于10000个字符',
    'requiredMessage': '请输入',
    'save': '保存',
    'validateForm': '验证表单',
    'pleaseInput': '请输入',
    'longTextRule': '长度限制',
    'numberRule': '数字',
    'pleaseSelect': '请选择',
    'auditSet': '审核设置',
    'operation': '操作',
    'more': '更多',
    'fileTypeNotRight': '文件类型不正确！',
    'auditSetAuditFormSet': '表单设置',
    'createTime': '创建时间',
    'confirm': '确认',
    'cancel': '取消',
    'back': '返回',
    'prompt': '提示',
    'saveEnable': '保存并启用',
    'workflowInfo': '页面信息',
    'workflowName': '页面名称',
    'description': '描述',
    'inputDescription': '请填写描述',
    'clickUpload': '点击上传',
    'formatRestrictionsNarrow': '只能上传jpg／png……80*80px',
    'addControlCreatorAudit': '从左边拖放控件到表单',
    'controlBase': '控件库',
    'singleLineInputBox': '单行输入框',
    'multilineInputBox': '多行输入框',
    'digitalInputBox': '数字输入框',
    'radio': '单选框',
    'checkbox': '多选框',
    'dateRange': '日期区间',
    'enclosure': '附件',
    'caption': '说明文字',
    'controlSet': '控件设置',
    'title': '标题',
    'pleaseEnter': '请输入',
    'promptText': '提示文字',
    'inputTitle': '请填写标题',
    'inputPromptText': '请填写提示文字',
    'content1000More': '内容最多可填写1000个字符',
    'singleLineInputBoxRule': '长度在0-1000个字符（单行输入框规则）',
    'content10000More': '内容最多可填写10000个字符',
    'verification': '验证',
    'requited': '必填',
    'requitedRule': '该项为必填项！',
    'selectTerm': '选项',
    'selectTermRule': '长度在0-40个字符（ 选项的规则）',
    '200MoreTerm40Character': '最多200项，每项最多40个字符',
    'inputSelectTerm': '请填写选项',
    'dateType': '日期类型',
    'yMDTM': '年-月-日 时:分',
    'yMD': '年-月-日',
    'lengthCalculation': '计算时长',
    'enable': '启用',
    'show': '显示',
    'check': '查看',
    'add': '添加',
    'multipleInputBox': '多行输入框',
    'text0To10Limit': '0-10个字符',
    'text0To40Limit': '0-40个字符',
    'textLength128': '最多输入128个字符',
    'required': '必填',
    'limit200MoreTerm40Character': '最多200项，每项最多40个字符',
    'cascadeInquire': '级联查询',
    'addRadio': '添加单选框',
    'followField': '跟随字段',
    'optionSource': '选项来源',
    'showField': '显示字段',
    'no': '暂无数据',
    'dataSource': '数据源',
    'delete': '删除',
    'canNotDeleteCascadeRadio': '无法删除，级联选择框至少有一个单选框！'
  },
  en: {
    'operateSuccess': 'Success!',
    'showAuth': 'show auth',
    'list': 'list',
    'inputField': 'input field',
    'fieldName': 'field name',
    'pageId': 'page id',
    'detail': 'detail',
    'edit': 'edit',
    'search': 'search',
    'numberMessage': 'input number',
    'longTextMessage': 'input less than 1000',
    'requiredMessage': 'please input',
    'save': 'save',
    'validateForm': 'validate form',
    'pleaseInput': 'please input',
    'longTextRule': 'length limit',
    'numberRule': 'number',
    'pleaseSelect': 'please select',
    'auditSet': 'audit set',
    'operation': 'operation',
    'more': 'more',
    'fileTypeNotRight': 'file type error',
    'auditSetAuditFormSet': 'form set',
    'createTime': 'created time',
    'confirm': 'confirm',
    'cancel': 'cancel',
    'back': 'back',
    'prompt': 'prompt',
    'saveEnable': 'save',
    'workflowInfo': 'page info',
    'workflowName': 'page name',
    'description': 'description',
    'inputDescription': 'input description',
    'clickUpload': 'click to upload',
    'formatRestrictionsNarrow': 'jpg/png only and size limit to 1000k',
    'addControlCreatorAudit': 'drag from left',
    'controlBase': 'components',
    'singleLineInputBox': 'input',
    'multilineInputBox': 'multiple input',
    'digitalInputBox': 'number input',
    'radio': 'select',
    'checkbox': 'multiple select',
    'dateRange': 'date range',
    'enclosure': 'attchment',
    'caption': 'info',
    'controlSet': 'setting',
    'title': 'title',
    'pleaseEnter': 'please enter',
    'promptText': 'prompt text',
    'inputTitle': 'input title',
    'inputPromptText': 'input prompt',
    'content1000More': 'less than 10000',
    'singleLineInputBoxRule': 'less than 10000',
    'content10000More': 'less than 10000',
    'verification': 'validation',
    'requited': 'required',
    'requitedRule': 'required!',
    'selectTerm': 'option',
    'selectTermRule': 'input 0 - 40',
    '200MoreTerm40Character': 'limit 200 and char less than 40',
    'inputSelectTerm': 'input option',
    'dateType': 'date type',
    'yMDTM': 'yyyy-mm-dd hh:mm',
    'yMD': 'yyyy-mm-dd',
    'lengthCalculation': 'time span',
    'enable': 'enable',
    'show': 'show',
    'check': '查看',
    'add': '添加',
    'multipleInputBox': 'multiple input',
    'text0To10Limit': '0-10',
    'text0To40Limit': '0-40',
    'textLength128': 'less than 120',
    'required': 'required',
    'limit200MoreTerm40Character': 'limit 200 and char less than 40',
    'cascadeInquire': 'cascade query',
    'addRadio': 'add select',
    'followField': 'follow',
    'optionSource': 'source',
    'showField': 'visible field',
    'no': 'no data',
    'dataSource': 'data source',
    'delete': 'delete',
    'canNotDeleteCascadeRadio': 'at least one option'
  }
}
export default all[cookie.get('lang') || 'cn']
