import cookie from 'Cookies'
var all = {
  en: {
    'operateSuccess': 'Success!',
    'showAuth': 'show auth',
    'list': 'list',
    'inputField': 'input field',
    'fieldName': 'field name',
    'pageId': 'page id',
    'detail': 'detail',
    'edit': 'edit',
    'search': 'search',
    'numberMessage': 'input number',
    'longTextMessage': 'input less than 1000',
    'requiredMessage': 'please input',
    'save': 'save',
    'validateForm': 'validate form',
    'pleaseInput': 'please input',
    'longTextRule': 'length limit',
    'numberRule': 'number',
    'pleaseSelect': 'please select',
    'auditSet': 'audit set',
    'operation': 'operation',
    'more': 'more',
    'fileTypeNotRight': 'file type error',
    'auditSetAuditFormSet': 'form set',
    'createTime': 'created time',
    'confirm': 'confirm',
    'cancel': 'cancel',
    'back': 'back',
    'prompt': 'prompt',
    'saveEnable': 'save',
    'workflowInfo': 'page info',
    'workflowName': 'page name',
    'description': 'description',
    'inputDescription': 'input description',
    'clickUpload': 'click to upload',
    'formatRestrictionsNarrow': 'jpg/png only and size limit to 1000k',
    'addControlCreatorAudit': 'drag from left',
    'controlBase': 'components',
    'singleLineInputBox': 'input',
    'multilineInputBox': 'multiple input',
    'digitalInputBox': 'number input',
    'radio': 'select',
    'checkbox': 'multiple select',
    'dateRange': 'date range',
    'enclosure': 'attchment',
    'caption': 'info',
    'controlSet': 'setting',
    'title': 'title',
    'pleaseEnter': 'please enter',
    'promptText': 'prompt text',
    'inputTitle': 'input title',
    'inputPromptText': 'input prompt',
    'content1000More': 'less than 10000',
    'singleLineInputBoxRule': 'less than 10000',
    'content10000More': 'less than 10000',
    'verification': 'validation',
    'requited': 'required',
    'requitedRule': 'required!',
    'selectTerm': 'option',
    'selectTermRule': 'input 0 - 40',
    '200MoreTerm40Character': 'limit 200 and char less than 40',
    'inputSelectTerm': 'input option',
    'dateType': 'date type',
    'yMDTM': 'yyyy-mm-dd hh:mm',
    'yMD': 'yyyy-mm-dd',
    'lengthCalculation': 'time span',
    'enable': 'enable',
    'show': 'show',
    'check': '查看',
    'add': '添加',
    'multipleInputBox': 'multiple input',
    'text0To10Limit': '0-10',
    'text0To40Limit': '0-40',
    'textLength128': 'less than 120',
    'required': 'required',
    'limit200MoreTerm40Character': 'limit 200 and char less than 40',
    'cascadeInquire': 'cascade query',
    'addRadio': 'add select',
    'followField': 'follow',
    'optionSource': 'source',
    'showField': 'visible field',
    'no': 'no data',
    'dataSource': 'data source',
    'delete': 'delete',
    'canNotDeleteCascadeRadio': 'at least one option'
  }
}
export default all[cookie.get('lang') || 'cn']
