/* eslint-disable */
var struct = {
  editor: {
    'operateSuccess': '操作成功！',
    'showAuth': '显示控制',
    'list': '列表',
    'inputField': '请输入字段名',
    'fieldName': '字段名',
    'pageId': '页面ID',
    'detail': '详情',
    'edit': '编辑',
    'search': '搜索',
    'number': '请输入数字',
    'longText': '请输入小于10000个字符',
    'save': '保存',
    'validateForm': '验证表单',
    'pleaseInput': '请输入',
    'longTextRule': '长度限制',
    'numberRule': '数字',
    'pleaseSelect': '请选择',
    'auditSet': '审核设置',
    'operation': '操作',
    'more': '更多',
    'fileTypeNotRight': '文件类型不正确！',
    'auditSetAuditFormSet': '表单设置',
    'createTime': '创建时间',
    'confirm': '确认',
    'cancel': '取消',
    'back': '返回',
    'prompt': '提示',
    'saveEnable': '保存并启用',
    'workflowInfo': '页面信息',
    'workflowName': '页面名称',
    'description': '描述',
    'inputDescription': '请填写描述',
    'clickUpload': '点击上传',
    'formatRestrictionsNarrow': '只能上传jpg／png……80*80px',
    'addControlCreatorAudit': '从左边拖放控件到表单',
    'controlBase': '控件库',
    'singleLineInputBox': '单行输入框',
    'multilineInputBox': '多行输入框',
    'digitalInputBox': '数字输入框',
    'radio': '单选框',
    'checkbox': '多选框',
    'dateRange': '时间选择器',
    'dateTime': '日期区间',
    'enclosure': '附件',
    'caption': '说明文字',
    'controlSet': '控件设置',
    'title': '标题',
    'pleaseEnter': '请输入',
    'promptText': '提示文字',
    'inputTitle': '请填写标题',
    'inputPromptText': '请填写提示文字',
    'content1000More': '内容最多可填写1000个字符',
    'singleLineInputBoxRule': '长度在0-1000个字符（单行输入框规则）',
    'content10000More': '内容最多可填写10000个字符',
    'verification': '验证',
    'requited': '必填',
    'requitedRule': '该项为必填项！',
    'selectTerm': '选项',
    'selectTermRule': '长度在0-40个字符（ 选项的规则）',
    '200MoreTerm40Character': '最多200项，每项最多40个字符',
    'inputSelectTerm': '请填写选项',
    'dateType': '日期类型',
    'yMDTM': '年-月-日 时:分',
    'yMD': '年-月-日',
    'lengthCalculation': '计算时长',
    'enable': '启用',
    'show': '显示',
    'check': '查看',
    'add': '添加',
    'multipleInputBox': '多行输入框',
    'text0To10Limit': '0-10个字符',
    'text0To40Limit': '0-40个字符',
    'textLength128': '最多输入128个字符',
    'required': '必填',
    'limit200MoreTerm40Character': '最多200项，每项最多40个字符',
    'cascadeInquire': '级联查询',
    'addRadio': '添加单选框',
    'followField': '跟随字段',
    'optionSource': '选项来源',
    'showField': '显示字段',
    'no': '暂无数据',
    'dataSource': '数据源',
    'delete': '删除',
    'canNotDeleteCascadeRadio': '无法删除，级联选择框至少有一个单选框！'
  },
  list: {
    '__detail__': '详情',
    '__delete__': '删除',
    '__edit__': '编辑',
    'numberMessage': '请输入数字',
    'longTextMessage': '请输入小于10000个字符',
    'requiredMessage': '请输入',
    'save': '保存',
    'cancel': '取消',
    'add': '新增',
    'editConfig': '编辑配置',
    'detail': '详情',
    'delete': '删除',
    'edit': '编辑',
    'operateSuccess': '操作成功',
    'operation': '操作',
    'more': '更多',
    'headerCols': [],
    'operateOpts': [
      {
        'label': '__edit__',
        'auth': 'edit'
      },
      {
        'label': '__detail__',
        'auth': 'detail'
      },
      {
        'label': '__delete__',
        'auth': 'delete'
      }
    ],
    'search': '搜索',
    'reset': '重置',
    'searchFields': []
  },
  admin: {
    module: '模块',
    editor: '编辑器',
    save: '保存',
    optionColor: '可选配色',
    cancel: '取消',
    color: '选择配色',
    configText: '配置文案',
    theme: '主题切换'
  }
}
export default struct
